/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package venta.reposteria;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Moises Dario
 */
public class DiseñoPago extends javax.swing.JFrame {

    private xFicheroPago file;
    
    public DiseñoPago() {
        initComponents();
        this.setLocationRelativeTo(null);
        //crea la instancia pasando como parametros los controles JTextField
        file = new xFicheroPago( this.txtNombreCliente, this.txtIdentificacionEspecial, this.txtNombreProducto, this.txtTamaño, this.txtPrecio,this.txtDescuentoAplicado1,this.txtImporte,this.txtCambio,this.txtTotalPagar );
        this.setTitle("" + file.getFileName());
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextFieldDescuentoAplicado = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCantidad = new javax.swing.JLabel();
        lblDescuento = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        lblTamañoPastel = new javax.swing.JLabel();
        lblDescuentoIncluido = new javax.swing.JLabel();
        txtTamaño = new javax.swing.JTextField();
        txtIdentificacionEspecial = new javax.swing.JTextField();
        txtNombreProducto = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtDescuentoAplicado1 = new javax.swing.JTextField();
        lblImagenCliente = new javax.swing.JLabel();
        btnCalcularResultado = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtImporte = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCambio = new javax.swing.JTextField();
        txtTotalPagar = new javax.swing.JTextField();
        txtDescuentoAplicado = new javax.swing.JTextField();
        btnCantidad = new javax.swing.JButton();
        btnVentanaPrincipal1 = new javax.swing.JButton();
        btnVentanaCliente1 = new javax.swing.JButton();
        btnDescuentoIncluido = new javax.swing.JButton();
        lblPrecioproducto1 = new javax.swing.JLabel();
        lblLugarVentas = new javax.swing.JLabel();
        lblPresentacionPago = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        TextFieldDescuentoAplicado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldDescuentoAplicadoActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCantidad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCantidad.setText("Cantidad:");

        lblDescuento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDescuento.setText("% de Descuento:");

        lblProducto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblProducto.setText("Producto:");

        lblTamañoPastel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTamañoPastel.setText("Tamaño del Pastel:");

        lblDescuentoIncluido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDescuentoIncluido.setText("Haga click, Incluye con descuento aplicado:");

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        txtDescuentoAplicado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoAplicado1ActionPerformed(evt);
            }
        });

        lblImagenCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/venta/reposteria/logo-pagoefectivo.png"))); // NOI18N

        btnCalcularResultado.setText("Aplicar descuento");
        btnCalcularResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcularResultadoMouseClicked(evt);
            }
        });
        btnCalcularResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularResultadoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Nombre del Cliente:");

        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Descuento aplicado:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Importe del pago:");

        txtImporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImporteActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Identificacion de Pastel Especial:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Cambio:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Total a pagar:");

        txtTotalPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPagarActionPerformed(evt);
            }
        });

        txtDescuentoAplicado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoAplicadoActionPerformed(evt);
            }
        });

        btnCantidad.setText("Cantidad Generada");
        btnCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCantidadMouseClicked(evt);
            }
        });
        btnCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantidadActionPerformed(evt);
            }
        });

        btnVentanaPrincipal1.setText("Finaliza la compra del cliente");
        btnVentanaPrincipal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentanaPrincipal1MouseClicked(evt);
            }
        });
        btnVentanaPrincipal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaPrincipal1ActionPerformed(evt);
            }
        });

        btnVentanaCliente1.setText("Modificar datos del cliente");
        btnVentanaCliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentanaCliente1MouseClicked(evt);
            }
        });
        btnVentanaCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaCliente1ActionPerformed(evt);
            }
        });

        btnDescuentoIncluido.setText("Usted va pagar");
        btnDescuentoIncluido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDescuentoIncluidoMouseClicked(evt);
            }
        });
        btnDescuentoIncluido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescuentoIncluidoActionPerformed(evt);
            }
        });

        lblPrecioproducto1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPrecioproducto1.setText("Precio de producto:");

        lblLugarVentas.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        lblLugarVentas.setText("SUCHIAPA, CHIAPAS");

        lblPresentacionPago.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblPresentacionPago.setText("Venta");

        btnLimpiar.setText("Limpiar ");
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDescuentoIncluido)
                        .addGap(18, 18, 18)
                        .addComponent(btnDescuentoIncluido)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCalcularResultado)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCantidad)
                                            .addComponent(lblProducto)
                                            .addComponent(lblTamañoPastel)
                                            .addComponent(btnCantidad)
                                            .addComponent(lblDescuento))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(116, 116, 116)
                                                .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtDescuentoAplicado1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(btnLimpiar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel8)
                                                            .addComponent(jLabel10)
                                                            .addComponent(jLabel11)
                                                            .addComponent(jLabel9))
                                                        .addGap(18, 18, 18))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel12)
                                                        .addGap(55, 55, 55)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtDescuentoAplicado, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtIdentificacionEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(213, 213, 213)
                                        .addComponent(lblImagenCliente))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(163, 163, 163)
                                        .addComponent(lblPresentacionPago)
                                        .addGap(391, 391, 391)
                                        .addComponent(lblLugarVentas)))))
                        .addContainerGap(300, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVentanaPrincipal1)
                    .addComponent(btnVentanaCliente1))
                .addGap(321, 321, 321))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(lblPrecioproducto1)
                    .addContainerGap(1847, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnCantidad)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProducto)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTamañoPastel))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescuento)
                    .addComponent(txtDescuentoAplicado1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalcularResultado)
                .addGap(66, 66, 66)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescuentoIncluido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDescuentoIncluido))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPresentacionPago)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLugarVentas)
                        .addGap(37, 37, 37)))
                .addComponent(lblImagenCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(txtIdentificacionEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVentanaCliente1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtDescuentoAplicado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnVentanaPrincipal1)))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(btnLimpiar))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(943, 943, 943))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(504, 504, 504)
                    .addComponent(lblPrecioproducto1)
                    .addContainerGap(1008, Short.MAX_VALUE)))
        );

        jMenu1.setText("Archivo");

        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("GuardarComo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(633, 633, 633))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1911, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1799, 1799, 1799)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularResultadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularResultadoMouseClicked

    private void btnCalcularResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularResultadoActionPerformed
        // Favor de escribir
       double num1 = Double.parseDouble(txtDescuentoAplicado1.getText());
       
       txtDescuentoAplicado.setText(String.valueOf(100-num1));
    }//GEN-LAST:event_btnCalcularResultadoActionPerformed

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void txtImporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImporteActionPerformed
          double num1 = Double.parseDouble(txtImporte.getText());
          double num2 = Double.parseDouble(txtTotalPagar.getText());
          
        txtCambio.setText(String.valueOf(num1-num2));
    }//GEN-LAST:event_txtImporteActionPerformed

    private void txtTotalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPagarActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtDescuentoAplicado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoAplicado1ActionPerformed
        //Favor de escribir
     
    }//GEN-LAST:event_txtDescuentoAplicado1ActionPerformed

    private void TextFieldDescuentoAplicadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldDescuentoAplicadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldDescuentoAplicadoActionPerformed

    private void btnCantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCantidadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCantidadMouseClicked

    private void btnCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantidadActionPerformed
        txtCantidad.setText("1");
    }//GEN-LAST:event_btnCantidadActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        String datos = "Nombre del Cliente: " + this.txtNombreCliente.getText() + "  " + " Identificacion del producto especial: " + this.txtIdentificacionEspecial.getText() + "  " + " Nombre del Producto: " +  this.txtNombreProducto.getText() + " " +" Tamaño del producto: " + this.txtTamaño.getText() + " " + "Precio del producto: " + this.txtPrecio.getText() + " " + " Descuento que aplica: " + this.txtDescuentoAplicado1 + " " + " Importe: " + this.txtImporte.getText() + " " + " Cambio: " + this.txtCambio.getText() + " " + " Total a Pagar: " + this.txtTotalPagar.getText();
        file.GuardarComo(datos);
        this.setTitle("" + file.getFileName() );
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        String datos = " ¡DATOS ACTUALIZADO ¡ " + "Nombre del Cliente: " + this.txtNombreCliente.getText() + "  " + " Identificacion del producto especial: " + this.txtIdentificacionEspecial.getText() + "  " + " Nombre del Producto: " +  this.txtNombreProducto.getText() + " " +" Tamaño del producto: " + this.txtTamaño.getText() + " " + "Precio del producto: " + this.txtPrecio.getText() + " " + " Descuento que aplica: " + this.txtDescuentoAplicado1 + " " + " Importe: " + this.txtImporte.getText() + " " + " Cambio: " + this.txtCambio.getText() + " " + " Total a Pagar: " + this.txtTotalPagar.getText();
        file.Actualizar(datos);
        this.setTitle("" + file.getFileName() );    
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnVentanaPrincipal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentanaPrincipal1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentanaPrincipal1MouseClicked

    private void btnVentanaPrincipal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaPrincipal1ActionPerformed
        DiseñoPasteles ventana = new DiseñoPasteles();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentanaPrincipal1ActionPerformed

    private void txtDescuentoAplicadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoAplicadoActionPerformed
         //Favor de escribir
         
    }//GEN-LAST:event_txtDescuentoAplicadoActionPerformed

    private void btnVentanaCliente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentanaCliente1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentanaCliente1MouseClicked

    private void btnVentanaCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaCliente1ActionPerformed
         DiseñoClientes ventana = new DiseñoClientes();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentanaCliente1ActionPerformed

    private void btnDescuentoIncluidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDescuentoIncluidoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDescuentoIncluidoMouseClicked

    private void btnDescuentoIncluidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescuentoIncluidoActionPerformed
         double num1 = Double.parseDouble(txtPrecio.getText());
         double num2 = Double.parseDouble(txtDescuentoAplicado.getText());
        txtTotalPagar.setText(String.valueOf((num1*num2)/100));
    }//GEN-LAST:event_btnDescuentoIncluidoActionPerformed

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtCambio.setText(" ");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiseñoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiseñoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiseñoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiseñoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiseñoPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldDescuentoAplicado;
    private javax.swing.JButton btnCalcularResultado;
    private javax.swing.JButton btnCantidad;
    private javax.swing.JButton btnDescuentoIncluido;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVentanaCliente1;
    private javax.swing.JButton btnVentanaPrincipal1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblDescuentoIncluido;
    private javax.swing.JLabel lblImagenCliente;
    private javax.swing.JLabel lblLugarVentas;
    private javax.swing.JLabel lblPrecioproducto1;
    private javax.swing.JLabel lblPresentacionPago;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblTamañoPastel;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescuentoAplicado;
    private javax.swing.JTextField txtDescuentoAplicado1;
    private javax.swing.JTextField txtIdentificacionEspecial;
    private javax.swing.JTextField txtImporte;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTamaño;
    private javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables
}
