/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package venta.reposteria;

/**
 *
 * @author Moises Dario
 */
public class DiseñoOrdenEntrega extends javax.swing.JFrame {

      private xFicheroOrdenEntrega file;
    public DiseñoOrdenEntrega() {
        initComponents();
        this.setLocationRelativeTo(null);
        //crea la instancia pasando como parametros los controles JTextField
        file = new xFicheroOrdenEntrega( this.txtNombreCliente.getText(),this.txtColonia.getText(), this.txtCiudad.getText(), this.txtTelefonoFijo.getText(), this.txtCorreo.getText(), this.txtObservacion.getText(), this.txtFechaEntrega.getText(), this.txtHoraEntrega.getText(), this.txtReferencias.getText(), this.txtIdentificacion.getText(), this.txtProducto.getText(), this.txtPrecio.getText(), this.txtDescuento.getText(), this.txtAnticipo.getText(), this.txtTotalPagar.getText(), this.txtImporte.getText(), this.txtCambio.getText() );
        this.setTitle("" + file.getFileName());
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPresentacionOrdenEntrega = new javax.swing.JLabel();
        lblApartadoPorducto = new javax.swing.JLabel();
        btnDescuentoIncluido = new javax.swing.JButton();
        txtNombreCliente = new javax.swing.JTextField();
        lblColonia = new javax.swing.JLabel();
        lblLugarOrdenEntrega = new javax.swing.JLabel();
        lblCiudad = new javax.swing.JLabel();
        lblTelefonoMovil = new javax.swing.JLabel();
        lblTelefonoFijo = new javax.swing.JLabel();
        lblObservaciones = new javax.swing.JLabel();
        lblHoraEntrega = new javax.swing.JLabel();
        lblFechaEntrega = new javax.swing.JLabel();
        lblReferencias = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        txtTelefonoFijo = new javax.swing.JTextField();
        txtColonia = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefonoMovil = new javax.swing.JTextField();
        lblIdentificacionEspecial = new javax.swing.JLabel();
        lblDescuentoIncluido8 = new javax.swing.JLabel();
        lblDescuentoAplicado = new javax.swing.JLabel();
        lblDescuentoAplicando = new javax.swing.JLabel();
        lblTotalPagra = new javax.swing.JLabel();
        lblAnticipo = new javax.swing.JLabel();
        btnVentanaPrincipal = new javax.swing.JButton();
        lblPrecio = new javax.swing.JLabel();
        lblImporte = new javax.swing.JLabel();
        lblCambio = new javax.swing.JLabel();
        txtFechaEntrega = new javax.swing.JTextField();
        txtHoraEntrega = new javax.swing.JTextField();
        txtReferencias = new javax.swing.JTextField();
        txtIdentificacion = new javax.swing.JTextField();
        txtProducto = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        txtDescuentoAplicado = new javax.swing.JTextField();
        txtAnticipo = new javax.swing.JTextField();
        txtTotalPagar = new javax.swing.JTextField();
        txtImporte = new javax.swing.JTextField();
        txtCambio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacion = new javax.swing.JTextArea();
        btnPagar = new javax.swing.JButton();
        btnCalcularAnticipo = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPresentacionOrdenEntrega.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblPresentacionOrdenEntrega.setText("Orden de Entrega");

        lblApartadoPorducto.setForeground(new java.awt.Color(0, 0, 204));
        lblApartadoPorducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/venta/reposteria/Apartado.png"))); // NOI18N

        btnDescuentoIncluido.setText("Aplicar descuento");
        btnDescuentoIncluido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDescuentoIncluidoMouseClicked(evt);
            }
        });
        btnDescuentoIncluido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescuentoIncluidoActionPerformed(evt);
            }
        });

        lblColonia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblColonia.setText("Colonia:");

        lblLugarOrdenEntrega.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        lblLugarOrdenEntrega.setText("SUCHIAPA, CHIAPAS");

        lblCiudad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCiudad.setText("Ciudad:");

        lblTelefonoMovil.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTelefonoMovil.setText("Telefono Movil:");

        lblTelefonoFijo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTelefonoFijo.setText("Telefono Fijo:");

        lblObservaciones.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblObservaciones.setText("Observacion:");

        lblHoraEntrega.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblHoraEntrega.setText("Hora de entrega:");

        lblFechaEntrega.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblFechaEntrega.setText("Fecha de entrega:");

        lblReferencias.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblReferencias.setText("Referencias:");

        lblNombreCliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNombreCliente.setText("Nombre del cliente:");

        lblCorreo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCorreo.setText("Correo:");

        lblIdentificacionEspecial.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblIdentificacionEspecial.setText("Identificacion del pastel especial:");

        lblDescuentoIncluido8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDescuentoIncluido8.setText("Producto:");

        lblDescuentoAplicado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDescuentoAplicado.setText("Descuento aplicado:");

        lblDescuentoAplicando.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDescuentoAplicando.setText("% Descuento:");

        lblTotalPagra.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTotalPagra.setText("Total a Pagar:");

        lblAnticipo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAnticipo.setText("Anticipo:");

        btnVentanaPrincipal.setText("Volver a Diseño de Pasteles");
        btnVentanaPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentanaPrincipalMouseClicked(evt);
            }
        });
        btnVentanaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaPrincipalActionPerformed(evt);
            }
        });

        lblPrecio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPrecio.setText("Precio:");

        lblImporte.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblImporte.setText("Importe:");

        lblCambio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCambio.setText("Cambio:");

        txtProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoActionPerformed(evt);
            }
        });

        txtDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoActionPerformed(evt);
            }
        });

        txtTotalPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPagarActionPerformed(evt);
            }
        });

        txtImporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImporteActionPerformed(evt);
            }
        });

        txtObservacion.setColumns(20);
        txtObservacion.setRows(5);
        jScrollPane1.setViewportView(txtObservacion);

        btnPagar.setText("Usted va pagar");
        btnPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPagarMouseClicked(evt);
            }
        });
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        btnCalcularAnticipo.setText("Con Anticipo");
        btnCalcularAnticipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcularAnticipoMouseClicked(evt);
            }
        });
        btnCalcularAnticipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularAnticipoActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCiudad)
                    .addComponent(lblCorreo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTelefonoMovil)
                        .addGap(363, 363, 363)
                        .addComponent(lblDescuentoIncluido8))
                    .addComponent(lblColonia)
                    .addComponent(lblTelefonoFijo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(497, 497, 497)
                .addComponent(lblPresentacionOrdenEntrega)
                .addGap(190, 190, 190)
                .addComponent(lblLugarOrdenEntrega)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreCliente)
                    .addComponent(lblObservaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                .addComponent(txtCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                .addComponent(txtColonia))
                            .addComponent(txtTelefonoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefonoMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblDescuentoAplicando)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPrecio)
                                            .addComponent(btnDescuentoIncluido)))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(13, 298, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblDescuentoAplicado, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblAnticipo, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblTotalPagra))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addComponent(btnPagar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblImporte))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnLimpiar)
                                    .addGap(39, 39, 39)
                                    .addComponent(lblCambio)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFechaEntrega)
                                    .addComponent(lblHoraEntrega)
                                    .addComponent(lblReferencias))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFechaEntrega)
                                    .addComponent(txtHoraEntrega)
                                    .addComponent(txtReferencias))
                                .addGap(231, 231, 231))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblIdentificacionEspecial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnVentanaPrincipal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDescuentoAplicado, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(txtAnticipo)
                                .addComponent(txtTotalPagar)
                                .addComponent(txtImporte))
                            .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalcularAnticipo)
                            .addComponent(lblApartadoPorducto))
                        .addContainerGap(37, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPresentacionOrdenEntrega)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreCliente)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaEntrega)
                            .addComponent(txtFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTelefonoMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefonoMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHoraEntrega)
                                    .addComponent(txtHoraEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblReferencias)
                                    .addComponent(txtReferencias, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTelefonoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefonoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIdentificacionEspecial)
                                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDescuentoAplicado))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDescuentoIncluido8)
                                .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblLugarOrdenEntrega)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnVentanaPrincipal)
                                    .addComponent(lblApartadoPorducto, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescuentoAplicado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txtAnticipo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCalcularAnticipo)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(lblImporte)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblCambio)
                                        .addComponent(btnLimpiar))
                                    .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblObservaciones))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDescuentoAplicando)
                                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addComponent(btnDescuentoIncluido)
                                .addGap(25, 25, 25))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAnticipo)
                                .addGap(61, 61, 61)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTotalPagra)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPagar)
                            .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Guardar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("GuardarComo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 228, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDescuentoIncluidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDescuentoIncluidoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDescuentoIncluidoMouseClicked

    private void btnDescuentoIncluidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescuentoIncluidoActionPerformed
        double num1 = Double.parseDouble(txtDescuento.getText());
       
       txtDescuentoAplicado.setText(String.valueOf(100-num1));
    }//GEN-LAST:event_btnDescuentoIncluidoActionPerformed

    private void btnVentanaPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentanaPrincipalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentanaPrincipalMouseClicked

    private void btnVentanaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaPrincipalActionPerformed
        DiseñoPasteles ventana = new DiseñoPasteles();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentanaPrincipalActionPerformed

    private void txtProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoActionPerformed

    private void txtDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoActionPerformed

    private void btnPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPagarMouseClicked

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        double num1 = Double.parseDouble(txtPrecio.getText());
        double num2 = Double.parseDouble(txtDescuentoAplicado.getText());
        txtTotalPagar.setText(String.valueOf((num1*num2)/100));
    }//GEN-LAST:event_btnPagarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String datos = " ¡DATOS ACTUALIZADO ¡ " + " Nombre del cliente:" + this.txtNombreCliente.getText() + "  " + " Colonia: " + this.txtColonia.getText() + "  " + " Ciudad: " +  this.txtCiudad.getText() + " " + " Telefono Fijo: " + this.txtTelefonoFijo.getText() + " " + " Telefono Movil: " + this.txtCorreo.getText() + " " + " Correo: " + this.txtObservacion.getText() + " " + " Observaciones: " + this.txtObservacion.getText() + " " +"  Fecha de Entrega: " + this.txtFechaEntrega.getText()+ " " + " Hora de Entrega: " + this.txtHoraEntrega.getText() + " " + " Referencias: " + this.txtReferencias.getText() + " " + " Identificacion de pastel especial:  " + this.txtIdentificacion.getText() + " " + " Nombre del producto: " + this.txtProducto.getText() + " " + " Precio: " + this.txtPrecio.getText() +  " " + " Descuento: " + this.txtDescuento.getText()+ " " + " Anticipo: " + this.txtAnticipo.getText() + " " + "Total a pagar actual: " + this.txtTotalPagar.getText() + " " + " Importe: " + this.txtImporte.getText() + " " + " Cambio: " + this.txtCambio.getText();
        file.Actualizar(datos);
        this.setTitle("" + file.getFileName() );     
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         String datos = " Nombre del cliente:" + this.txtNombreCliente.getText() + "  " + " Colonia: " + this.txtColonia.getText() + "  " + " Ciudad: " +  this.txtCiudad.getText() + " " + " Telefono Fijo: " + this.txtTelefonoFijo.getText() + " " + " Telefono Movil: " + this.txtCorreo.getText() + " " + " Correo: " + this.txtObservacion.getText() + " " + " Fecha de Entrega: " + this.txtFechaEntrega.getText()+ " " + " Hora de Entrega: " + this.txtHoraEntrega.getText() + " " + " Referencias: " + this.txtReferencias.getText() + " " + " Identificacion de pastel especial:  " + this.txtIdentificacion.getText() + " " + " Nombre del producto: " + this.txtProducto.getText() + " " + " Precio: " + this.txtPrecio.getText() +  " " + " Descuento: " + this.txtDescuento.getText()+ " " + " Anticipo: " + this.txtAnticipo.getText() + " " + "Total a pagar actual: " + this.txtTotalPagar.getText() + " " + " Importe: " + this.txtImporte.getText() + " " + " Cambio: " + this.txtCambio.getText();
         file.GuardarComo(datos);
        this.setTitle("" + file.getFileName() );
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txtTotalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPagarActionPerformed

    private void btnCalcularAnticipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularAnticipoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularAnticipoMouseClicked

    private void btnCalcularAnticipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularAnticipoActionPerformed
        double num1 = Double.parseDouble(txtAnticipo.getText());
        double num2 = Double.parseDouble(txtTotalPagar.getText());
        txtTotalPagar.setText(String.valueOf(num2 - num1));
    }//GEN-LAST:event_btnCalcularAnticipoActionPerformed

    private void txtImporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImporteActionPerformed
        double num1 = Double.parseDouble(txtImporte.getText());
        double num2 = Double.parseDouble(txtTotalPagar.getText());
          
        txtCambio.setText(String.valueOf(num1-num2));
    }//GEN-LAST:event_txtImporteActionPerformed

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtCambio.setText(" ");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiseñoOrdenEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiseñoOrdenEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiseñoOrdenEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiseñoOrdenEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiseñoOrdenEntrega().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularAnticipo;
    private javax.swing.JButton btnDescuentoIncluido;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnVentanaPrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnticipo;
    private javax.swing.JLabel lblApartadoPorducto;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblColonia;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDescuentoAplicado;
    private javax.swing.JLabel lblDescuentoAplicando;
    private javax.swing.JLabel lblDescuentoIncluido8;
    private javax.swing.JLabel lblFechaEntrega;
    private javax.swing.JLabel lblHoraEntrega;
    private javax.swing.JLabel lblIdentificacionEspecial;
    private javax.swing.JLabel lblImporte;
    private javax.swing.JLabel lblLugarOrdenEntrega;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPresentacionOrdenEntrega;
    private javax.swing.JLabel lblReferencias;
    private javax.swing.JLabel lblTelefonoFijo;
    private javax.swing.JLabel lblTelefonoMovil;
    private javax.swing.JLabel lblTotalPagra;
    private javax.swing.JTextField txtAnticipo;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtDescuentoAplicado;
    private javax.swing.JTextField txtFechaEntrega;
    private javax.swing.JTextField txtHoraEntrega;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtImporte;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextArea txtObservacion;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtReferencias;
    private javax.swing.JTextField txtTelefonoFijo;
    private javax.swing.JTextField txtTelefonoMovil;
    private javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables
}
