/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package venta.reposteria;

/**
 *
 * @author Moises Dario
 */
public class IdentificacionPasteles extends javax.swing.JFrame {

    /**
     * Creates new form IdentificacionPasteles
     */
    public IdentificacionPasteles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPresentacionDescuento = new javax.swing.JLabel();
        lblPresentacionPasteles1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEspeciales = new javax.swing.JList<>();
        lblRemate = new javax.swing.JLabel();
        lblPresentacionPasteles2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnVentanaDiseñoProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(204, 0, 204));

        lblPresentacionDescuento.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblPresentacionDescuento.setText("Identificacion de \"Pasteles Especiales\"");

        lblPresentacionPasteles1.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        lblPresentacionPasteles1.setText("Descuento de todos los productos de Pasteles Especiales:");

        jListEspeciales.setBackground(new java.awt.Color(102, 255, 255));
        jListEspeciales.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 255)));
        jListEspeciales.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jListEspeciales.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "\t\t\t\tSpecial Cake \" *** Pastel Especial *** \"", "#: 1 Nombre del pastel: Special Orange \t\"Zanahoria\" \tidentificacion especial: 1260", "#: 2 Nombre del pastel: Special Yellow  \t\"Vainilla\"     \tidentificacion especial: 1240", "#: 3 Nombre del pastel: Special Fresitas \t\"Fresas\"     \tidentificacion especial: 1230", "#: 4 Nombre del pastel: Special Gaspar \t\"Tiramisu\"   \tidentificacion especial: 1284", "#: 5 Nombre del pastel: Special Brown \t\"Chocolate\"   \tidentificacion especial: 1290", "#: 6 Nombre del pastel: Special Adorno \t\"Tres Leche\" \tidentificacion especial: 1295", "#: 7 Nombre del pastel: Special RedGood \t\"Red Velvelt\"\tidentificacion especial: 1293 " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListEspeciales);

        lblRemate.setForeground(new java.awt.Color(0, 0, 204));
        lblRemate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/venta/reposteria/Gran Remate del Producto.jpg"))); // NOI18N

        lblPresentacionPasteles2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblPresentacionPasteles2.setText("Identificacion de \"Pasteles Especiales\"");

        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/venta/reposteria/40%.jpg"))); // NOI18N

        btnVentanaDiseñoProducto.setText("Volver a diseño de producto");
        btnVentanaDiseñoProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentanaDiseñoProductoMouseClicked(evt);
            }
        });
        btnVentanaDiseñoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaDiseñoProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPresentacionDescuento)
                    .addComponent(lblPresentacionPasteles1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRemate)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPresentacionPasteles2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                        .addComponent(btnVentanaDiseñoProducto)
                        .addGap(65, 65, 65))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(1055, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(290, 290, 290)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblPresentacionPasteles2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(lblPresentacionDescuento)
                        .addGap(164, 164, 164))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVentanaDiseñoProducto)
                        .addGap(110, 110, 110)
                        .addComponent(lblRemate, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)))
                .addComponent(lblPresentacionPasteles1)
                .addGap(112, 112, 112))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(659, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentanaDiseñoProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentanaDiseñoProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentanaDiseñoProductoMouseClicked

    private void btnVentanaDiseñoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaDiseñoProductoActionPerformed
        DiseñoPasteles ventana = new DiseñoPasteles();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentanaDiseñoProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IdentificacionPasteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IdentificacionPasteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IdentificacionPasteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IdentificacionPasteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IdentificacionPasteles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVentanaDiseñoProducto;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jListEspeciales;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPresentacionDescuento;
    private javax.swing.JLabel lblPresentacionPasteles1;
    private javax.swing.JLabel lblPresentacionPasteles2;
    private javax.swing.JLabel lblRemate;
    // End of variables declaration//GEN-END:variables
}
